Models/survey.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AutomatedSurvey.Models
{
    public class survey
    {

        public String EmployeeId { get; set; }

        public string Name { get; set; }


        public List<QuestionsModel> Questions { get; set; }
        public List<AnswerModel> Answers { get; set; }

        public class QuestionsModel
        {
            public string QuestionText { get; set; }
            public string QuestionComment { get; set; }

        }
        public class AnswerModel
        {
            public string AnswerText { get; set; }
            public bool IsCorrect { get; set; }
        }
    }
}

Models/surveydata.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AutomatedSurvey.Models
{
    public class surveydata
    {
        public List<QuestionsModel> Questions { get; set; }
        public List<AnswerModel> Answers { get; set; }

        public class QuestionsModel
        {
            public string QuestionText { get; set; }
            public string QuestionComment { get; set; }

        }
        public class AnswerModel
        {
            public string AnswerText { get; set; }
            public bool IsCorrect { get; set; }
        }

    }
}

Models/surveylist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AutomatedSurvey.Models
{
    public class surveylist : survey
    {
        public List<State_list> State { get; set; }

        public List<City_list> City { get; set; }

        public List<Department_list> Department { get; set; }

    }


    public class State_list
    {
        public int State_ID { get; set; }

        public string State_Name { get; set; }
    }

    public class City_list
    {
        public int City_Id { get; set; }

        public string City_Name { get; set; }
    }

    public class Department_list
    {
        public int Dept_Code { get; set; }

        public string Dept_Name { get; set; }
    }



}

Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedSurvey.Controllers
{
    public class AnswersController : Controller
    {
        // GET: Answers
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedSurvey.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedSurvey.Controllers
{
    public class QuestionsController : Controller
    {
        // GET: Questions
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SurveyController.cs
using System.Linq;
using System.Web.Mvc;



namespace AutomatedSurvey.Web.Controllers
{
    public class SurveyController : Controller
    {

        public ActionResult Survey()
        {
            return View();
        }


        public ActionResult Surveyquestion()
        {
            return View();
        }


        public ActionResult Addsurvey()
        {
            return View();
        }



        public ActionResult Manage()
        {
            return View();
        }


       // public ActionResult 




        //private readonly IRepository<Survey> _surveysRepository;
        //private readonly IRepository<Answer> _answersRepository;

        //public SurveyController() : this(new SurveyRepository(), new AnswerRepository()) { }

        //public SurveyController(
        //    IRepository<Survey> surveysRepository, IRepository<Answer> answersRepository)
        //{
        //    _surveysRepository = surveysRepository;
        //    _answersRepository = answersRepository;
        //}





        //public ActionResult Results()
        //{
        //    var answers = _answersRepository.All();
        //    var uniqueAnswers = answers;


        //    ViewBag.UniqueAnswers = uniqueAnswers;
        //    ViewBag.SurveyTitle = _surveysRepository.FirstOrDefault().Title;
        //    return View(answers);
        //}
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Manage", "Manage", "Survey")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Survey/Addsurvey.cshtml
@{
    ViewBag.Title = "Addsurvey";
}

<h2>Create Question</h2>


<form name="ProForm">


    <div class="form-group">
        <label>Question :</label>

        <input type="text" id="Text" class="form-control" />

    </div>

    <div>
        @Html.ActionLink("Create", "Manage")
    </div>

</form>




@*
    <!doctype html>
        <html lang="en">
        <head>
            <meta charset="utf-8">
            <title>show Questions</title>


                <script type="text/javascript">
                    $("#btnadd").click(function () {
                        $("body").show();

                    });
                </script>



        </head>

            <div>

                <input id="btnadd" type="button" value="Add" onclick="Addquestion()" name="ID" />


                <body>

                <div id="users" style="display: none">
                    <div>
                        First Name:
                        <input type="text" id="FirstName" />
                    </div><br />
                    <div>
                        Last Name:
                        <input type="text" id="LastName" />
                    </div><br />
                    <div>
                        Username:
                        <input type="text" id="UserName" />
                    </div><br />
                    <div>
                        Password:
                        <input type="password" id="Password" />
                    </div><br />
                    <div>
                        Role:
                        <input type="checkbox" id="Role">Beginner
                        <input type="checkbox" id="Role"> Advanced
                        <input type="checkbox" id="Role"> Expert
                    </div>





                </div>

                    </body>
            </div>
            </html>*@


@*


        <div id="example" style="border: 1px solid rgb(204, 204, 204); margin: 5px 0pt; padding: 5px;">Question :</div>
        <form>
            <div><textarea class="example-default-value" id="example-textarea" style="width: 400px; height: 50px;"></textarea></div>
            <div><input type="button" value="Add" onclick="example_append()" /></div>

        </form>

        <div id="example1" style="border: 1px solid rgb(204, 204, 204); margin: 5px 0pt; padding: 5px;">Question Type:</div>
        <form>
            <div>
                <input class="dropdown" id="example-textarea1"></input>
            </div>
            <div><input type="button" value="Add" onclick="example_append1()" /></div>

        </form>
        <script language="javascript">
            $('.example-default-value').each(function () {
                var default_value = this.value;
                $(this).focus(function () {
                    if (this.value == default_value) {
                        this.value = '';
                    }
                });
                $(this).blur(function () {
                    if (this.value == '') {
                        this.value = default_value;
                    }
                });
            });
            function example_append() {
                $('#example').append($('#example-textarea').val());
            }
            function example_append1() {
                $('#example1').append($('#example-textarea1').val());
            }
        </script>
    </head>
    </html>*@

Views/Survey/Manage.cshtml
<html>

<body>

    <div>
        <h1>Survey Questions</h1>

        <a href="~/Survey/Survey">Create A Question</a>
    </div>
</body>


</html>

Views/Survey/Survey.cshtml
@{
    ViewBag.Title = "Survey";
}

<h2>Create Question</h2>


<form name="ProForm">

    
        <div class="form-group">
            <label>Question :</label>

            <input type="text" id="Text" class="form-control" />

        </div>

        <div>
            @Html.ActionLink("Create", "Addsurvey")
        </div>
   
    </form>

Views/Survey/Surveyquestion.cshtml
@model AutomatedSurvey.Models.survey

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>survey</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="btn btn-default">
                @Html.ActionLink("Start", "Addsurvey")
            </div>
        </div>
    </div>
}